[package]
name = "fuck"
version = "0.1.0"
authors = ["KaiserLancelot <1244713586@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
